server.port: 9002

spring.boot.admin:
  url: http://localhost:9001
  username: ${security.user.name}
  password: ${security.user.password}
  client:
    metadata:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: admin
    password: admin